language: cpp
dist: trusty
sudo: required
before_install:
  - sudo apt-get install python3
  - sudo apt-get install python-pip
  - sudo pip install requests
  - sudo apt-get install libboost-all-dev
script: make test