language: cpp
dist: trusty
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo pip3 install requests
  - sudo apt-get install libboost-all-dev
script: make test