language: cpp
dist: trusty
sudo: required
before_install:
  - sudo apt-get update
  - sudo pip install requests
  - sudo apt-get install libboost-all-dev
  # Fix for python failing to import module
  # Pulled from here: https://github.com/travis-ci/travis-ci/issues/5679
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
script: make test

